services:
  prisma_db:
    image: mysql:latest
    container_name: prisma
    ports:
      - 3306:3306
    volumes:
      - myvolume:/var/lib/mysql
    networks:
      - mynet
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
networks:
  mynet:
    name: prisma_net
volumes:
  myvolume:
    name: prisma_vol
